#ifndef MEMORY_AT91SAM7X256_H
#define MEMORY_AT91SAM7X256_H

#define VERSION			0x0103

#define MAIN_MODE_CHECK_MS	500

typedef enum __attribute__ ((packed)) 
{
	MAIN_MODE_NONE = 0,
	MAIN_MODE_EMAC,
	MAIN_MODE_MEMORY,
	MAIN_MODE_AUTONOM,
} main_mode_type;


extern void ErrorHalt(u32 code);

inline void delay(u32 d) { for (u32 i = 0; i < d; i++) __nop(); }

enum 
{
	ERROR_EMAC_PHY_ID		= 0	,
	ERROR_EMAC_ERX0_LOW			,	
	ERROR_EMAC_ERX1_LOW			,		
	ERROR_EMAC_ERX2_LOW			,	
	ERROR_EMAC_ERX3_LOW			,	
	ERROR_EMAC_ERXER_LOW		,	
	ERROR_EMAC_PWRDN_LOW		,	
	ERROR_EMAC_ERXCK_LOW		,	
	ERROR_EMAC_ERXDV_LOW		,	
	ERROR_EMAC_EMDC_LOW			,	// 9	

	ERROR_EMAC_EMDIO_LOW		,	// 10
	ERROR_EMAC_ETX0_LOW			,	
	ERROR_EMAC_ETX1_LOW			,	
	ERROR_EMAC_ETX2_LOW			,
	ERROR_EMAC_ETX3_LOW			,
	ERROR_EMAC_ETXCK_LOW		,
	ERROR_EMAC_ETXEN_LOW		,
	ERROR_EMAC_ETXER_LOW		,	// 17

	ERROR_EMAC_ERX0_HI		= 30,	// 30	
	ERROR_EMAC_ERX1_HI			,		
	ERROR_EMAC_ERX2_HI			,		
	ERROR_EMAC_ERX3_HI			,		
	ERROR_EMAC_ERXER_HI			,		
	ERROR_EMAC_PWRDN_HI			,		
	ERROR_EMAC_ERXCK_HI			,		
	ERROR_EMAC_ERXDV_HI			,		
	ERROR_EMAC_EMDC_HI			,		
	ERROR_EMAC_EMDIO_HI			,	

	ERROR_EMAC_ETX0_HI			,	// 40
	ERROR_EMAC_ETX1_HI			,
	ERROR_EMAC_ETX2_HI			,
	ERROR_EMAC_ETX3_HI			,	
	ERROR_EMAC_ETXCK_HI			,
	ERROR_EMAC_ETXEN_HI			,
	ERROR_EMAC_ETXER_HI			,

	ERROR_EMAC_ERX0_SHORT	= 60,	// 30	
	ERROR_EMAC_ERX1_SHORT		,		
	ERROR_EMAC_ERX2_SHORT		,		
	ERROR_EMAC_ERX3_SHORT		,		
	ERROR_EMAC_ERXER_SHORT		,		
	ERROR_EMAC_PWRDN_SHORT		,		
	ERROR_EMAC_ERXCK_SHORT		,		
	ERROR_EMAC_ERXDV_SHORT		,		
	ERROR_EMAC_EMDC_SHORT		,		
	ERROR_EMAC_EMDIO_SHORT		,	// 69	

	ERROR_EMAC_ETX0_SHORT		,	// 70
	ERROR_EMAC_ETX1_SHORT		,
	ERROR_EMAC_ETX2_SHORT		,
	ERROR_EMAC_ETX3_SHORT		,	
	ERROR_EMAC_ETXCK_SHORT		,
	ERROR_EMAC_ETXEN_SHORT		,
	ERROR_EMAC_ETXER_SHORT			// 76
};								



#endif
